### ISSUE TITLE
Some small QOL things.

### ISSUE THREAD

**Issue by maxybaer123** [FTBTeam/FTB-Sky-Odyssey#124]
Please consider doing some of the following ran into all of these as issues at some point.

Look into disabling RM tools AOE mine lost a ton of stuff to the void when I accidentally right clicked with my mace and the pack already has vein miner.

Deep mob learnings guide book is dependent upon Patchouli which is not in the pack.

The castle map and perhaps a few others require architecture craft stairs which are hard to use and cant be copy pasted Vanilla Builders extension adds in some extra stairs and slabs which could replace this as well as being a nice addition to the decorative options in the pack.

An addition the the guide that specifies what is or isn't an EMC exploit for example ore doubling is/isn't an exploit. I didn't ore double at first because i was worried it was an overlooked exploit or something.

Also you might want to stop game over bags dropping from WOOT factories it seems a little OP especially since they can drop creative item dispenser upgrades.

**Comment by Slowpoke101** [comment]
1. This is a valuable life lesson that believe me we have all learned at one point.  The lesson is 'don't charge tools you can't control'

2. This is fixed in the next version.

3. The pack has been optimised an awful lot. Adding a new mod that hasn't been tested is not something I want to do at this stage, however I am going to look at that mod for another pack we have in development.
