### ISSUE TITLE
space bar to skip intro doesn't always work or requires repeated input

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Sky-Odyssey#173]
* **Modpack Version**:  1.0.0

* **Issue**: Pressing space to skip the intro requires repeated input and sometimes doesn't work at all.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f24b6a3b

* **Is it Repeatable?**: yep

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Excederus** [comment]
I think that is a Minecraft issue instead of a issue fixable by modpack creators.
It's due to Minecraft skipping inputs when you have less than around 5fps. (Also happens when you try to use a shader on a high render distance and you have like 3fps and you wonder why you cant click on the options in graphics settings)

**Comment by manmaed** [comment]
iirc the credits are being removed in the next update. in the mean time you could remove the animation file

**Comment by Rushmead** [comment]
The introduction credits are being removed in the next update. If you wish to skip them, for now you can simply remove the "animation" folder from your modpack's instance folder or remove the "SplashAnimation" mod from the modpack.
