### ISSUE TITLE
World Corrupted?

### ISSUE THREAD

**Issue by Beep-BoopBop** [FTBTeam/FTB-Sky-Odyssey#316]
* **Modpack Version**: 1.0.0

* **Issue**: Whenever I try to open my world, it crashes before it loads a single percentage and states, 'The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Ticking block entity'

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/92d04f7c

* **Is it Repeatable?**: Every time I attempt to load my world, yes

**Comment by nzminecraftDOTcom** [comment]
Looks like you have a ticking entity: Do this
To remove erroring entities (Mobs - skeletons etc) and tile entities (Pistons, crafting tables, interactive blocks...)

######Single player:######
Close out of your game completely.
Do a world/save backup before proceeding.
Go to the config folder for the modpack, look for forge.cfg
######Server:######
Close the server down fully using /stop
Backup ALL relevant files you have, worlds, configs etc.
Go to the relevant config file for the modpack having the issue - Locate "forge.cfg"

Find the lines:

"Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES."

Set this part to true:
B:removeErroringEntities=true

AND

"Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES."

Set this part to true:
B:removeErroringTileEntities=true

Now start your game and load the world. If all went well it should load just fine. You should now try to do what you were doing when the crash occured. If that succeeds. Stop your game, and reset both those settings back to false. If you have issues further on, you can try leaving them on true but heed the warnings they state in their description.

**Comment by Beep-BoopBop** [comment]
That seems to have worked! However, my inventory and everything stored in my ProjectE Transmutation Table seems to have disappeared. But at least the game will launch now.

**Comment by Naxanria** [comment]
It is a world corruption, not much we can do about. Glad you can get it working again :)
