### ISSUE TITLE
Flux Network. Charging not working

### ISSUE THREAD

**Issue by Alsososcar** [FTBTeam/FTB-Sky-Odyssey#496]
Modpack Version: 1.2.0

Issue: Flux Networks. When i set charging in inventory it just auto set it off

Is it Repeatable: Yes, Every time i try its just happening again.

Mod/s Affected**: Flux Networks

Known Fix: No i dont have one

**Comment by Srslyhamerd** [comment]
This is part of either the 1.2.0 update or a new version of flux networks, if you hover over the inventory bit in wireless charging it clearly says (Disabled). Meaning it will not turn on. No fix needed it is intentional. 
![image](https://user-images.githubusercontent.com/55206270/86525634-c7b23a80-be57-11ea-9a33-69691017e0eb.png)

**Comment by Alsososcar** [comment]
Yeah but when i try to activate ut it do not want to turn on.. i know ut
saus it disabled but i click it then apply. And update the page it says
disabled again..

søn. 5. jul. 2020, 06:37 skrev Srslyhamerd <notifications@github.com>:

**Comment by Srslyhamerd** [comment]
Again, that is because it is Disabled, as in that part of the program is no longer there, Inventory charging is no longer a feature.
Hotbar, Bauble, Main Hand, Off Hand only.

It can not be activated, the feature was removed. it doesn't say (Disabled) because it's off, it says (Disabled) because either the mod or modpack creator removed the feature.
