### ISSUE TITLE
Hostile Mobs don't spawn in chosen architecht island

### ISSUE THREAD

**Issue by WalshamP** [FTBTeam/FTB-Sky-Odyssey#68]
No hostile mobs are spawning.  Checked with F7, Red crosses and no mobs.

**Comment by Philipp766** [comment]
when i built a mobfarm away from the platform, monsters spawned. but i had so far no luck in the chambers below the island, but maybe i gave the mobs no time to spawn

**Comment by Firefox37** [comment]
are you using cursed earth? else the spawning area will need to be 24 blocks away from your general working area

**Comment by Philipp766** [comment]
i built a mobfarm 24 blocks out, but broke the glowstones in the floor. i think i just was too little away for any spawning to happen in the cursed earth pits

**Comment by TheOfficialButton** [comment]
To get Hostile mobs to spawn you need to be atleast 24 blocks away from your spawn platform.

**Comment by jk1895** [comment]
I have the same issue but on the castle island. No stupid mobs. I cheated cursed earth and replaced the cobblestone floor with them. 
I tried a new world and it was the same. Room is dark and high enough. I'm at least 24 blocks away.
I hate this bug because it's rare and the packmakers are thinking we are dumb or something.
