### ISSUE TITLE
Using Emc links with AE2 autocrafting hangs world

### ISSUE THREAD

**Issue by Basedgod199** [FTBTeam/FTB-Sky-Odyssey#84]
Whenever i ask my ae2 system to auto-craft something that needs to pull from an emc link, it will hang my world. I've tried using multiple different settings in the storage bus, and I've tried using all 3 emc links, as well as a few different items to auto-craft, every time it needs something from the emc link, it will hang.

**Comment by qoolies** [comment]
i just have the same question as you ,It because ae2 system can't handle huge number items...

**Comment by Jake-E** [comment]
We think this is currently an AE2 issue.
Attempting some fixes with the EMC Link to see if we can get it working better.

**Comment by udooles** [comment]
I am having the same issue.  Autocrafting from the items in the EMC link causes the game to go to a waiting for server state forever and I have to force quit out of the game.

I looked in the configs to see if there was a way to lower the number of items EMC links present as storage from 2 billion to a lower number like 100,000 but didn't see a option.

**Comment by madmacf** [comment]
I have the same problem.

**Comment by Firefox37** [comment]
According to LatvianModder's Github, it seems that the issue is in the file [TileLink.java](https://github.com/LatvianModder/Project-EX/blob/master/src/main/java/com/latmod/mods/projectex/tile/TileLink.java)

On line 201, `int c = getCount(knowledgeProvider, value, 2000000000);` the int limit value can be decreased. Not sure if that is the same file on the currently-used version of the mod.

However, this would only be a band-aid fix, as I assume the main issue is with AE2 as it should be able to handle any autocraft request with any amount of items (potentially below the 32-bit Java integer limit) in the inventory; which 2 billion is below that value.

Not sure if this fix is the one you are testing in dev, but posted here just to have a temporary solution while waiting for the potential AE2 fix.

**Comment by kaspermwh** [comment]
> 
> 
> According to LatvianModder's Github, it seems that the issue is in the file [TileLink.java](https://github.com/LatvianModder/Project-EX/blob/master/src/main/java/com/latmod/mods/projectex/tile/TileLink.java)
> 
> On line 201, `int c = getCount(knowledgeProvider, value, 2000000000);` the int limit value can be decreased. Not sure if that is the same file on the currently-used version of the mod. However, as a better idea, instead of hard-coding the value, have it an option in the config where the user can choose how many items are provided by the EMC link (this obviously, would be a more substantial change than just changing a number).
> 
> However, this would only be a band-aid fix, as I assume the main issue is with AE2 as it should be able to handle any autocraft request with any amount of items (potentially below the 32-bit Java integer limit) in the inventory; which 2 billion is below that value.
> 
> Not sure if this fix is the one you are testing in dev, but posted here just to have a temporary solution while waiting for the potential AE2 fix.

is it possible to implement this fix myself?

**Comment by Basedgod199** [comment]
Latvian put out a new version of ProjectEx, version 1.1.0.18, there's an option in the config file to change the value. I changed mine to 200k, works just fine.
