### ISSUE TITLE
NBT to long after dieing and losing connection

### ISSUE THREAD

**Issue by Firemaster177** [FTBTeam/FTB-Sky-Odyssey#85]
![image](https://user-images.githubusercontent.com/48750043/54667854-11d0aa80-4ab3-11e9-9d4a-aae864e60a2d.png)
This is all i see when trying to reconnect to my server, my friend is able to remain on the server fine and has no issues in the server, this is all i see.

**Comment by CastielAngelow** [comment]
Are you using provided Vanilla server or SpongeForge? This happening pretty often on some NBT heavy modpacks on Spongeforge. Mostly because of "Graves List of lost items" that internally basically generates "twice" your inventory, and if its full, well. Cannot really "help you" and doubt it will but try to adding this to your JVM Startup Parameters
`-XX:+UnlockExperimentalVMOptions -Dfml.readTimeout=180 -Dio.netty.leakDetection.level=advanced`.
Probably won't help, but provide also your server.log file when this happen. It is a "bit" necessary to see logs most of the time to know what exactly caused it. If it was grave mod and youre able to, edit your player nbt data in server files.

**Comment by Jake-E** [comment]
As a note, `-Dfml.readTimeout=180` does not work on Forge 1.12.2.
Need more info to diagnose this.

**Comment by Slowpoke101** [comment]
Have you managed to resolve this?
